spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.32.242:3306/logdemo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
#mybatis:
#  type-aliases-package: com.example.logdemo.test.domain
#  mapper-locations: classpath*:/com/example/logdemo/test/mapper/xml/*.xml